//MAGIC8BALL!!!
function magic8ball(){
  var magic8ballResponses = [];
    //can create new responses and add arrays below
    magic8ballResponses[0] = 'Yes..!';
    magic8ballResponses[1] = 'nope.';
    magic8ballResponses[2] = 'maybe....not too sure';
    magic8ballResponses[3] = 'Yes.....DEFINITELY!';
    magic8ballResponses[4] = 'Hahaha...  no';
    magic8ballResponses[5] = 'Sorry..but no..';
    magic8ballResponses[6] = 'Without a doubt.';

      //generates a random number based on array length
      var randomResponse = Math.floor(Math.random() * magic8ballResponses.length);
      //generates random response based on the random number generated from random response.Outputs a response
      var randomResponseOutput = magic8ballResponses[randomResponse];
      //Returns a response generated by the program
      return randomResponseOutput;
}

// console.log(magic8ball()) <=== testing random responses (remove comment tags to test in console.log)

//variables for locating the dom
var userResponse = document.querySelector('#userResponse');     //MAGIC8BALL WILL RESPONSE!
var userInput = document.querySelector('#userInput');           //The text box
var userBtn = document.querySelector('#userBtn');               //The button!

//click event to generate a response
userBtn.addEventListener('click',function(){

  var userInputValue = userInput.value;

  if (userInputValue === ''){
    userResponse.textContent = '* Please write a response.';
  } else if (userInputValue == Number(userInputValue)){
    userResponse.textContent = '* Please write a question';
  } else {
    userInput.value = '';
    userResponse.textContent = magic8ball();
  }
});
